# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-21 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_share',
            field=models.BooleanField(default=False),
        ),
    ]
